name: securechat
description: "Application de messagerie sécurisée avec chiffrement AES-256 et salons temporaires"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  crypto: ^3.0.0
  pointycastle: ^3.9.1
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: ^0.68.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  flutter_riverpod: ^2.4.9
  http: ^1.2.0
  uuid: ^4.3.3
  supabase_flutter: ^2.9.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
